Import('env')

hook_lib_env = env.Clone()
hook_lib_env.AppendUnique(
    LIBS = ["dl", "pthread"],
    CPPDEFINES = "_GNU_SOURCE",
)

sources = [
    'libc_hooks.c',
]

hook_lib = hook_lib_env.SharedLibrary(
    'flyr-hook.so',
    source = sources,
)
